In [2]:
import numpy as np 
import warnings
warnings.filterwarnings("ignore")#sürüm ile değişen kavramlarla ilgili uyarıları göstermemesi için kullanıyoruz.İgnore ingilizcede aldırma anlamına gelir

In [3]:
list1=[10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [4]:
type(list1)

list

In [6]:
arr1=np.array(list1) #list1 numpy dizisi haline geldi

In [7]:
arr1

array([10, 20, 30, 40, 50, 60])

In [8]:
#bellekteki adresini aşağıdaki gibi bulurum
arr1.data

In [9]:
type(arr1) # type görüntü tipini verir. ndarray dir

numpy.ndarray

In [11]:
arr1.dtype #veri tipini verir

dtype('int32')

In [13]:
arr1.astype(float) #astype ile veri türünü değiştirebiliriz

array([10., 20., 30., 40., 50., 60.])

In [14]:
np.arange(0,10) #arange 0-10 arasında sayıları oluşturur

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,100,10)#0 dan 100 e kadar 10 ar 10 ar artan

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
np.arange(100,0,-10)#yukarıdakinin tam tersi

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [18]:
arr3=np.arange(0,10) #tek boyutludur şekli.Bunu 10,1 olarak düşünebiliriz
arr3.shape

(10,)

In [19]:
arr3.size  

10

In [20]:
arr3.ndim

1

In [21]:
#10 a 1 olduğunu yukarıdakilerle de teyit edebiliriz